# Generated by Django 2.2 on 2020-06-07 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 15, 32, 44, 75135), verbose_name='消息发送时间'),
        ),
    ]
