# Generated by Django 2.2 on 2020-06-07 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200607_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 15, 50, 58, 268848), verbose_name='消息发送时间'),
        ),
        migrations.AlterField(
            model_name='operate_class',
            name='etime',
            field=models.DateTimeField(null=True, verbose_name='处理时间'),
        ),
    ]
