# Generated by Django 3.1.7 on 2021-03-07 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210304_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 14, 21, 49, 61663), verbose_name='消息发送时间'),
        ),
    ]
