# Generated by Django 3.1.7 on 2021-03-08 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210308_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 10, 11, 23, 610797), verbose_name='消息发送时间'),
        ),
    ]
